---
vagrantfile:
    box: centos7
    hosts:
      - master
      - minion-1
    master:
        role: master
        ip: 172.28.128.10
    minion-1:
        role: minion
        ip: 172.28.128.11
    synced_folder:
        devops:
            source: .
            target: /srv/
    auth:
        private_key: /home/iliya/.ssh/id_dsa
    provision:
        salt: ./salt-bootstrap.sh
